### ISSUE TITLE
Version mismatch in CMakeLists

### ISSUE THREAD

**Issue by sidsbrmnn** [akielaries/openGPMP#37]
https://github.com/akielaries/openMTPK/blob/ecf824d5063e61e7a7fa99116c98506235a46a6a/CMakeLists.txt#L38

I believe the latest project version is `0.9.7` according to PyPI and `0.9.4` according to GitHub release tags. `CMakeLists.txt` stills points to `0.5`. Perhaps we can keep all these version numbers in sync somehow.

**Comment by akielaries** [comment]
This is a good point. I wonder if we could just omit the version number for CMake. If not it could be nice to perhaps make it dynamic by including it into some sort of pipeline.

**Comment by sidsbrmnn** [comment]
I'm looking to publish a RPM for the package in the Fedora Project, making it available for use as `dnf install openmtpk`. I was able to build the package successfully but at the cost of some changes (like making the libopenMTPK shared instead of static, adding `-fPIC` to compilation flags for tests and making use of `gtest` from a system level and not fetch directly from CMake).

The last one was majorly because Fedora builds happen inside a `chroot` environment and networking is natively disabled. I'll create a different project for the said Fedora builds and share it with you for you to review.

As for the changes, let them be as patch for now for the builds I'm taking. Once they look good and are reviewed by you, you can pull them into the upstream. I'd also like to discuss with you more about the package publishing.

**Comment by akielaries** [comment]
Thank you very much for doing this! This is pretty cool. In terms of making openMTPK a static vs shared library, it doesn't matter too much to me, there are benefits to both and it would take some maturing of the project to really boil down our use cases. These changes are very much welcome and I'd love to review them! Thank you for all your help so far. Feel free to open a separate issue or continue this thread to discuss about the package publishing.

In response to this earlier statement...
> I believe the latest project version is 0.9.7 according to PyPI and 0.9.4 according to GitHub release tags

So far, the versions for the Python API and the actual source code are to be treated differently at the moment. The source code gets updated more frequently than the Python API and mostly to avoid constantly publishing new versions to PyPI, in this early stage it can't be helped as we're trying to get things right regarding the CI/CD pipeline currently in place

**Comment by akielaries** [comment]
solved in #99 by fetching the dirty git tag using `git describe --tags` from the `CMakeLists.txt` file
