### ISSUE TITLE
Duplicate header files include/ml/encoder_var.hpp

### ISSUE THREAD

**Issue by sidsbrmnn** [akielaries/openGPMP#38]
Files [encoder.hpp](include/ml/encoder.hpp) and [encoder_var.hpp](include/ml/encoder_var.hpp) are duplicates. I'm not sure if this was intended or by accident.

**Comment by akielaries** [comment]
You are correct, these are duplicates maybe we want to stick with the [`encoder.hpp`](https://github.com/akielaries/openMTPK/blob/main/include/ml/encoder.hpp). In all honesty the Machine Learning module is in quite a hectic state. Perhaps it would have been better for me to only include the working pieces of this module (I believe only the Linear Regression method is in a working state)
